# Generated by Django 2.1.2 on 2018-10-31 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_post_moder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='moder',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AddField(
            model_name='comment',
            name='user_name',
            field=models.CharField(default=None, max_length=15, verbose_name='Имя пользователя'),
        ),
        migrations.AddField(
            model_name='comment',
            name='vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='comment',
            table=None,
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
